### ISSUE TITLE
Exception in thread MessageReceiver and OSError: [Errno 9]

### ISSUE THREAD

**Issue by eabase** [Queeq/pydtc#2]
Running a simple example code using:
```python
from pydtc import dtc_download
data = dtc_download('EURUSD', start_date='2020.12.20', server=("0.0.0.0", 11098), debug=True)
header = next(data)
print(header)
```

results in the following error:

```python
Downloading data:  95%|█████████▌| 5.58k/5.85k [00:01<00:00, 5.22krecords/s]

Exception in thread MessageReceiver:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/pathto/pydtc/venv/lib/python3.8/site-packages/pydtc/main.py", line 216, in run
    self.selector.select()
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
OSError: [Errno 9] Bad file descriptor
{'exchange': 'Bitcoin', 'symbol': 'EURUSD', 'rec_interval': 60}
```

SC Log shows:
```text
HD Server Manager | Incoming connection from IP: 127.0.0.1 | 2020-12-24  23:45:15.420
HD Server Manager | Started new historical data server. Count=1 | 2020-12-24  23:45:15.421
HD Server | Thread:12716 (2) | Creating socket. | 2020-12-24  23:45:15.423
HD Server | Thread:12716 (2) | New receive buffer size: 262144 | 2020-12-24  23:45:15.423
HD Server | Setting DTC encoding to Protocol Buffers | Thread:12716 | 2020-12-24  23:45:15.423
HD Server | Thread:12716 (2) | Allocated send buffers: 31 of 4096 bytes. | 2020-12-24  23:45:15.423
HD Server | Received login. Requesting authorization. | Username: wat. | Thread:12716 | 2020-12-24  23:45:15.431
HD Server | Login has been authorized. | Username: wat. | Thread:12716 | 2020-12-24  23:45:15.431
HD Server | HD Request #1 | Socket: 2 | Symbol: EURUSD | ServiceCode: Bitcoin | RecordInterval: 60 | MaximumDaysRequested: 0 | Start date-time: 2020-12-20  00:00:00 | ClientReqID: 1 | Username: wat. | Thread:12716 | 2020-12-24  23:45:15.431
HD Server | HD Request | Socket: 2 | Symbol: EURUSD | ServiceCode: Bitcoin | RecordInterval: 60 | Records Served: 5542 | ClientReqID: 1 | Username: wat. | Thread:12716 | 2020-12-24  23:45:15.508
HD Server | Thread:12716 (2) | Socket gracefully closed by remote side. | 2020-12-24  23:45:16.697
HD Server | Thread:12716 (2) | CloseSocket call. | 2020-12-24  23:45:16.697
HD Server | Thread:12716 (2) | 0 bytes remaining in receive buffer when socket closed. | 2020-12-24  23:45:16.697
HD Server | Thread:12716 (0) | CloseSocket call. | 2020-12-24  23:45:16.698
HD Server | Thread:12716 (2) | Graceful close received or receive error. Shutdown complete. Closing socket now. | 2020-12-24  23:45:16.698
HD Server | Thread:12716 (2) | Closed. | 2020-12-24  23:45:16.698
HD Server | Thread:12716 (0) | CloseSocket call. | 2020-12-24  23:45:16.698
HD Server | Server thread ending. Closing socket. | Username: wat. | Thread:12716 | 2020-12-24  23:45:16.846
HD Server Manager | Current server count=0 | 2020-12-24  23:45:16.846
```
 
Any idea what is the problem? Fix?

**Comment by Queeq** [comment]
I guess it may be because `0.0.0.0` is not the valid IP address to connect to. Try to specify `127.0.0.1`?

**Comment by eabase** [comment]
> I guess it may be because `0.0.0.0` is not the valid IP address to connect to. Try to specify `127.0.0.1`?

Not at all, the download proceeds and prints, but IP that is a different SC weirdness. (They actually don't make it clear how they use the ports in the SC config. Just naming it generally in the settings.) From my tests on other python connections to other trading SW, I found out that 0.0.0.0 usually refers to .NET socket **pipe**, whereas 127.0.0.1 refer to a TCP connection. ^^ so 127.0.0.1, never worked for me on SC. 

But if you look at the error, it seem to origin from a thread, and that there are several threads started. Looking at the Log you also see that it's trying to shutdown at least 2 more threads. Maybe threading should not be used in the download? IDK.

**Comment by eabase** [comment]
PS. It also seem that the `OSError: [Errno 9] Bad file descriptor` error is most often associated with trying to do something with already closed sockets.

**Comment by Queeq** [comment]
Oh, you must be on Windows. I only tested it on Linux and Mac, so no idea how it would behave there.

There are indeed several threads for parallelism (all spawned by `DtcConnection`):
- `DTCMessageReceiver`: listens for incoming packets. Puts them in `self.messages` deque and signals via `self.data_arrival_event` upon first incoming historical data message.
-  `DTCProtobufHeartbeat`: spawned if connection is not for historical data (I don't remember why I did it).
- `DtcDownloadWatcher`: watches download progress and is used for metering. This is the one showing the progress bar.

So your exception comes from the first one, i.e. it can't listen for messages any longer. And maybe you're right, the socket is closed by then. From the SC log it looks like it serves records just fine and then pydtc closes the connection normally. I'd suspect there's some race condition, i.e. connection is closed while `DTCMessageReceiver` is still doing something (shouldn't happen though because the first thing `DtcConnection.disconnect()` does is stops the receiver).

Could you post the full debug log? Possibly with very small amount of data by setting very recent date.

**Comment by eabase** [comment]
> Could you post the full debug log? Possibly with very small amount of data by setting very recent date.

You mean from Python or from SC? (from python there is nothing more, really, and what's missing from the SC log, seem irrelevant.)

Also, IIRC there are some options (3?) for the threads where you can specify if it should be blocking/waiting etc. But not sure this has anything to do with this issue.

**Comment by Queeq** [comment]
When you set `debug=True` in `dtc_download()` it should result in very verbose output where pretty much every step and every message is logged. You may need to enable logging in the calling script using something like this:
```python
import logging

logging.basicConfig(format='{asctime} {name} {threadName} {levelname}: {message}', style='{')
```

This is how normal historical data download should look like:
```
2021-01-01 12:15:39,448 pydtc MainThread DEBUG: Receiver initialized
2021-01-01 12:15:39,448 pydtc MainThread DEBUG: Sent encoding request
2021-01-01 12:15:39,492 pydtc MessageReceiver DEBUG: Received encoding response
2021-01-01 12:15:39,493 pydtc MessageReceiver DEBUG: {
  "ProtocolVersion": 8,
  "Encoding": "PROTOCOL_BUFFERS",
  "ProtocolType": "DTC"
}
2021-01-01 12:15:39,493 pydtc MainThread DEBUG: Sent logon request
2021-01-01 12:15:39,494 pydtc MessageReceiver DEBUG: Received logon response
2021-01-01 12:15:39,494 pydtc MessageReceiver DEBUG: {
  "ProtocolVersion": 7,
  "Result": "LOGON_SUCCESS",
  "ResultText": "Logon successful. Compression not supported.",
  "ServerName": "SC HistoricalDataServer",
  "OrderCancelReplaceSupported": 1,
  "HistoricalPriceDataSupported": 1,
  "MarketDepthIsSupported": 1,
  "OneHistoricalPriceDataRequestPerConnection": 1
}
2021-01-01 12:15:39,494 pydtc MainThread DEBUG: Receiver buffer: 0 message(s)
2021-01-01 12:15:39,494 pydtc MainThread DEBUG: Sent historical data request
2021-01-01 12:15:39,503 pydtc MessageReceiver DEBUG: Received historical data response header
2021-01-01 12:15:39,503 pydtc MessageReceiver DEBUG: {
  "RequestID": 1,
  "RecordInterval": "INTERVAL_1_MINUTE"
}
2021-01-01 12:15:39,504 pydtc MessageReceiver DEBUG: Received historical data record response
2021-01-01 12:15:39,504 pydtc MessageReceiver DEBUG: {
  "RequestID": 1,
  "StartDateTime": "1609455604",
  "OpenPrice": 29135.25,
  "HighPrice": 29161.4609375,
  "LowPrice": 29084.48046875,
  "LastPrice": 29086.470703125,
  "Volume": 43886.0,
  "NumTrades": 36,
  "BidVolume": 40804.0,
  "AskVolume": 3082.0
}

<more historical data records>

Downloading data: 100%|█████████▉| 778/779 [00:00<00:00, 5.10krecords/s]
{'exchange': 'Bitcoin', 'symbol': 'BTC-BSTMP', 'rec_interval': 60}
2021-01-01 12:15:39,854 pydtc DownloadWatcher DEBUG: DownloadWatcher: reception complete
2021-01-01 12:15:39,854 pydtc DownloadWatcher DEBUG: Disconnecting from DTC server

```

As for thread options, I'm not sure what you mean. Thread synchronization is usually achieved using built-in primitives like locks, conditions, semaphores, events, etc.

**Comment by eabase** [comment]
Ah, yes, that line was needed.

```
$ ./example.py

Calling DTC download...


Printing header:

2021-01-02 00:25:12,532 pydtc MainThread DEBUG: Receiver initialized
2021-01-02 00:25:12,532 pydtc MainThread DEBUG: Sent encoding request
2021-01-02 00:25:12,535 pydtc MessageReceiver DEBUG: Received encoding response
2021-01-02 00:25:12,535 pydtc MessageReceiver DEBUG: {
  "ProtocolVersion": 8,
  "Encoding": "PROTOCOL_BUFFERS",
  "ProtocolType": "DTC"
}
2021-01-02 00:25:12,542 pydtc MainThread DEBUG: Sent logon request
2021-01-02 00:25:12,543 pydtc MessageReceiver DEBUG: Received logon response
2021-01-02 00:25:12,543 pydtc MessageReceiver DEBUG: {
  "ProtocolVersion": 8,
  "Result": "LOGON_SUCCESS",
  "ResultText": "Logon successful. Compression not supported.",
  "ServerName": "SC HistoricalDataServer",
  "OrderCancelReplaceSupported": 1,
  "HistoricalPriceDataSupported": 1,
  "MarketDepthIsSupported": 1,
  "OneHistoricalPriceDataRequestPerConnection": 1
}
2021-01-02 00:25:12,543 pydtc MainThread DEBUG: Receiver buffer: 0 message(s)
2021-01-02 00:25:12,543 pydtc MainThread DEBUG: Sent historical data request
2021-01-02 00:25:12,544 pydtc MessageReceiver DEBUG: Received historical data response header
2021-01-02 00:25:12,544 pydtc MessageReceiver DEBUG: {
  "RequestID": 1,
  "RecordInterval": "INTERVAL_1_MINUTE"
}
2021-01-02 00:25:12,544 pydtc MessageReceiver DEBUG: Received historical data record response
2021-01-02 00:25:12,545 pydtc MessageReceiver DEBUG: {
  "RequestID": 1,
  "StartDateTime": "1609437668",
  "OpenPrice": 1.2222950458526611,
  "HighPrice": 1.2225300073623657,
  "LowPrice": 1.2221800088882446,
  "LastPrice": 1.2225099802017212,
  "Volume": 239.0,
  "NumTrades": 239,
  "BidVolume": 94.0,
  "AskVolume": 145.0
}

...

Downloading data:   4%|▎         | 60.0/1.70k [00:00<00:00, 6.89krecords/s]
2021-01-02 00:25:12,669 pydtc DownloadWatcher DEBUG: DownloadWatcher: reception complete
2021-01-02 00:25:12,669 pydtc DownloadWatcher DEBUG: Disconnecting from DTC server
Exception in thread MessageReceiver:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/cygdrive/xxxx/pydtc/venv/lib/python3.8/site-packages/pydtc/main.py", line 216, in run
    self.selector.select()
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
OSError: [Errno 9] Bad file descriptor
{'exchange': 'anyShitOk', 'symbol': 'EURUSD', 'rec_interval': 60}
done
```

**Comment by Queeq** [comment]
OK, so the reception completes just fine, it only fails on the very last stage when connection is being closed. I think it's reasonable to simply catch this exception. Could you try this patch?

```diff
diff --git a/pydtc/main.py b/pydtc/main.py
index 77047d9..a33ef48 100644
--- a/pydtc/main.py
+++ b/pydtc/main.py
@@ -213,7 +213,17 @@ class DTCMessageReceiver(InterruptibleThread):
         """ Receive a message and then wait for signal to receive other messages """
         while self.running:
             # Listen for input event on the socket
-            self.selector.select()
+            try:
+                self.selector.select()
+            except OSError as e:
+                # It might happen in the end of reception that we're trying to read the socket that is closed in the
+                # middle of select() (seems to be the case on Windows)
+                if not self.running:
+                    return
+                else:
+                    log.error("Can't listen to IO events (`select()` failed), the network socket must be closed. "
+                              "MessageReceiver will exit now. The error was: {}".format(e))
+                    return
             self._get_message()

     def _get_message(self):
```

**Comment by eabase** [comment]
Cool! That fixed it. 

BTW. Where does that log message `"Can't listen to IO events..."` go? I don't see it in the *logger* output.

**Comment by Queeq** [comment]
Cool, I'll push the proper change to the repository later.

That error would only be displayed if `self.running` is `True`: it means that there's something wrong while the connection is expected to be working. Under normal circumstances `self.running` is set to `False` in the end of the session, but before the socket is closed, so it shouldn't even reach that `select()` function because the while loop is terminated. However, in your case something is happening with the socket before the connection is actually closed and before MessageReceiver's `running` flag is set to `False`, hence it cycles the loop one more time. By the time it reaches `select()`, `self.running` is already set to `False` which I consider normal operation, so if exception occurs the error is not displayed as we're supposed to terminate the whole thing anyway.

**Comment by eabase** [comment]
> Cool, I'll push the proper change to the repository later.

Great! But you probably want to update the DTC file `DTCProtocol_pb2.py` from version 7 to 8, as well.

Download latest files with:
```bash
#!/usr/bin/env bash
dfiles=(DTCProtocol.h DTCProtocol.cpp DTCProtocolVLS.h DTCProtocolVLS.cpp DTCProtocol.proto)
durl="https://dtcprotocol.org/DTC_Files/"
for f in "${dfiles[@]}"; do u="${durl}${f}"; echo -n "Downloading: ${u}"; curl -kLOs "${u}" && echo "  ok"; done;
echo "Done"
```

Then:
```bash
# Create a "new" DTCProtocol_pb2.py
protoc --python_out=. DTCProtocol.proto 
```

:arrow_up:  **This has been moved to issue #4**
